In [1]:
from os.path import join, dirname, exists
from os import makedirs
from itertools import chain, islice
from thesis_v2 import dir_dict
from thesis_v2.configs.model.maskcnn_polished_with_rcnn_k_bl import main_models_ns2250_generator
from thesis_v2.analysis.io import collect_rcnn_k_bl_main_result
from thesis_v2.analysis.ns2250 import load_ccmax

In [2]:
import pandas as pd

In [3]:
import numpy as np
cell_classification = [
    'unknown',
    'v2',
    'v1',
    'unknown',
    'v2',
    
    'v2',
    'v1',
    'v2',
    'unknown',
    'v1',
    
    'unknown',
    'unknown',
    'v2',
    'v2',
    'unknown',
    
    
    'v2',
    'v2',
    'unknown',
    'unknown',
    'unknown',
    
    'v2',
    'unknown',
    'v1',
    'v2',
    'v2',
    
    'v1',
    'v2',
    'v2',
    'v2',
    'v2',
    
    'v2',
    'v1',
    'v2',
    'unknown'
]

mask = np.array(cell_classification) == 'v1'
assert mask.shape == (34,)

In [4]:
def load_new_result():
    f_main_result = join(dir_dict['analyses'], 'ns2250', 'main', 'perf_v1.pkl')
    if not exists(f_main_result):
        makedirs(dirname(f_main_result), exist_ok=True)
        df_main_result = collect_rcnn_k_bl_main_result(
            fixed_keys = {
            'kernel_size_l23': 3,
            'kernel_size_l1': 9,
            'ff_1st_block': True,
            'pooling_ksize': 3,
            'pooling_type': 'avg',
            'bn_after_fc': False,
            'rcnn_bl_psize': 1,
            'rcnn_bl_ptype': None,
            'input_size': 37,
            'split_seed': 'legacy',
            'dataset_prefix': 'tang',
            'model_prefix': 'maskcnn_polished_with_rcnn_k_bl',
            'scale_name': '0.01',
            'scale': '0.01',
            'smoothness_name': '0.000005',
            'smoothness': '0.000005',
                'additional_key': '0,500'
        },
            generator=chain(
                main_models_ns2250_generator(with_source=True),
            ),
            total_num_param=27,
            train_size_mapping=dict(),
            no_missing_data=True,
            cc_max_all_neurons=load_ccmax(),
            num_neuron=mask.sum(),
            skip_eval_json=True,
            mask=mask,
        )
        df_main_result.to_pickle(f_main_result)
        del df_main_result
    df_main_result = pd.read_pickle(f_main_result)
    return df_main_result

In [5]:
df_main_result_new = load_new_result()
df_main_result_new

[[45  1]
 [91  1]
 [12  1]
 [71  1]
 [84  1]
 [ 2  1]
 [28  1]
 [25  1]
 [74  1]
 [31  1]
 [64  1]
 [77  1]
 [41  1]
 [ 8  1]
 [70  1]
 [40  0]
 [80  1]
 [14  1]
 [60  1]
 [57  1]
 [37  1]
 [83  1]
 [36  0]
 [30  1]
 [40  1]
 [17  1]
 [79  1]
 [43  1]
 [13  1]
 [ 3  1]
 [49  1]
 [16  1]
 [88  1]
 [68  1]]
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400

                                                                                                              cc2_normed_avg  \
act_fn   ff_1st_bn_before_act loss_type model_seed num_layer out_channel rcnn_bl_cls readout_type train_keep
relu     False                mse       0          2         8           1           cm-avg       350               0.218011
                                                                                                  700               0.271743
                                                                                                  1400              0.307790
                                                                                     cm-last      350               0.218011
                                                                                                  700               0.271743
...                                                                                                                      ...
softplus True                 poisson   1          6         16          1           legacy       700               0.321633
                                                                                                  1400              0.380582
                                                             32          1           legacy       350               0.268192
                                                                                                  700               0.319628
                                                                                                  1400              0.398334

                                                                                                              cc2_raw_avg  \
act_fn   ff_1st_bn_before_act loss_type model_seed num_layer out_channel rcnn_bl_cls readout_type train_keep
relu     False                mse       0          2         8           1           cm-avg       350            0.207476
                                                                                                  700            0.258813
                                                                                                  1400           0.293017
                                                                                     cm-last      350            0.207476
                                                                                                  700            0.258813
...                                                                                                                   ...
softplus True                 poisson   1          6         16          1           legacy       700            0.305766
                                                                                                  1400           0.361446
                                                             32          1           legacy       350            0.255087
                                                                                                  700            0.303812
                                                                                                  1400           0.378053

                                                                                                              cc_raw_avg  \
act_fn   ff_1st_bn_before_act loss_type model_seed num_layer out_channel rcnn_bl_cls readout_type train_keep
relu     False                mse       0          2         8           1           cm-avg       350           0.393084
                                                                                                  700           0.461224
                                                                                                  1400          0.491577
                                                                                     cm-last      350           0.393084
                                                                                                  700           0.461224
...                                                                                                                  ...
softplus True                 poisson   1          6         16          1           legacy       700           0.515006
                                                                                                  1400          0.576189
                                                             32          1           legacy       350           0.452864
                                                                                                  700           0.513224
                                                                                                  1400          0.594667

                                                                                                              num_param
act_fn   ff_1st_bn_before_act loss_type model_seed num_layer out_channel rcnn_bl_cls readout_type train_keep
relu     False                mse       0          2         8           1           cm-avg       350              4972
                                                                                                  700              4972
                                                                                                  1400             4972
                                                                                     cm-last      350              4972
                                                                                                  700              4972
...                                                                                                                 ...
softplus True                 poisson   1          6         16          1           legacy       700             16988
                                                                                                  1400            16988
                                                             32          1           legacy       350             53580
                                                                                                  700             53580
                                                                                                  1400            53580

[8496 rows x 4 columns]